import scrapy


class SiteItem(scrapy.Item):
    domain = scrapy.Field()
    platform = scrapy.Field()
    url = scrapy.Field()
    content_encode = scrapy.Field()
    title = scrapy.Field()
    meta = scrapy.Field()
    site_name = scrapy.Field()
    index_url = scrapy.Field()
    description = scrapy.Field()
    snapshot = scrapy.Field()
    name = scrapy.Field()
    path = scrapy.Field()
    image_hash = scrapy.Field()
    last_status = scrapy.Field()
    first_publish_time = scrapy.Field()
    last_publish_time = scrapy.Field()
    service_type = scrapy.Field()
    is_recent_online = scrapy.Field()
    scale = scrapy.Field()
    active_level = scrapy.Field()
    label = scrapy.Field()
    goods_label = scrapy.Field()
    goods_count = scrapy.Field()
    pay_methods = scrapy.Field()
    goods_user_count = scrapy.Field()
    site_hazard = scrapy.Field()
    user_info = scrapy.Field()
    lang = scrapy.Field()
    net_type = scrapy.Field()
