import scrapy


class UserItem(scrapy.Item):
    uuid = scrapy.Field()
    user_id = scrapy.Field()
    platform = scrapy.Field()
    domain = scrapy.Field()
    user_name = scrapy.Field()
    user_nickname = scrapy.Field()
    user_description = scrapy.Field()
    url = scrapy.Field()
    identity_tags = scrapy.Field()
    register_time = scrapy.Field()
    last_active_time = scrapy.Field()
    goods_orders = scrapy.Field()
    level = scrapy.Field()
    member_degree = scrapy.Field()
    ratings = scrapy.Field()
    user_img = scrapy.Field()
    topic_nums = scrapy.Field()
    post_counts = scrapy.Field()
    area = scrapy.Field()
    user_verification = scrapy.Field()
    user_order_count = scrapy.Field()
    user_viewed_count = scrapy.Field()
    user_feedback_count = scrapy.Field()
    user_followed_count = scrapy.Field()
    user_related_url_and_address = scrapy.Field()
    user_related_images = scrapy.Field()
    user_related_files = scrapy.Field()
    user_recent_day = scrapy.Field()
    user_related_crawl_tags = scrapy.Field()
    emails = scrapy.Field()
    bitcoin_addresses = scrapy.Field()
    eth_addresses = scrapy.Field()
    user_hazard_level = scrapy.Field()
    lang = scrapy.Field()
    net_type = scrapy.Field()
    crawl_time = scrapy.Field()
